In [8]:
import numpy as np

# 1.Create a numpy array of size 2 x 2
arr22=np.empty((2,2))
print("Empty NumPy array created by np.empty:\n")
print(arr22)
# 2.Create a random numpy array of size 3 x 4
# arrRand34=np.random.rand(3,4) random floats from [0,1)
arrRand34=np.random.randint(0,100,(3,4)) # random integers from [0,99]
print("Random NumPy array of size 3 x 4:\n")
print(arrRand34)
# 3.Create a numpy array of ones and a numpy array of zeroes
arr0=np.zeros((2,2))
arr1=np.ones((4,4))
print("A numpy array of ones(4 \u00D7 4):\n")
print(arr1)
print("A numpy array of zeros(2 \u00D7 2):\n")
print(arr0)
# 4.Create a random numpy array of size 6x3 and transpose it
arrR63=np.random.rand(6,3)
arrT=arrR63.T
print("A random numpy array(6 \u00D7 3):\n")
print(arrR63)
print("A numpy array transposed from the one above(3 \u00D7 6):\n")
print(arrT)
# 5.Create two random numpy array of size n x p and p x m and then compute the dot product
n=int(input("please enter the num of rows of the first matrix:"))
p=int(input("please enter the num of columns of the first matrix or of rows of the second matrix:"))
m=int(input("please enter the num of columns of the first matrix:"))
# arrnp=np.random.rand(n,p) floats
# arrpm=np.random.rand(p,m) floats

#integers from [0,49]
arrnp=np.random.randint(0,50,(n,p))
arrpm=np.random.randint(0,50,(p,m))
arrnm=arrnp @ arrpm
print("\nHere are the results of Question 5:\n")
print(1,arrnp,2,arrpm,3,arrnm,sep='\n',end='\n')

Empty NumPy array created by np.empty:

[[0. 0.]
 [0. 0.]]
Random NumPy array of size 3 x 4:

[[82 97 68 10]
 [64 60 31 90]
 [20 51 29 70]]
A numpy array of ones(4 × 4):

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
A numpy array of zeros(2 × 2):

[[0. 0.]
 [0. 0.]]
A random numpy array(6 × 3):

[[4.08234360e-01 5.07355114e-03 8.64915183e-02]
 [7.04226392e-01 5.26093096e-01 3.35761903e-01]
 [1.63889422e-04 4.10246520e-01 2.45437406e-01]
 [1.50757488e-01 9.22476001e-01 2.74692510e-01]
 [4.85483325e-01 9.81921467e-02 7.72964279e-01]
 [5.60451338e-01 6.50990184e-02 5.03165791e-01]]
A numpy array transposed from the one above(3 × 6):

[[4.08234360e-01 7.04226392e-01 1.63889422e-04 1.50757488e-01
  4.85483325e-01 5.60451338e-01]
 [5.07355114e-03 5.26093096e-01 4.10246520e-01 9.22476001e-01
  9.81921467e-02 6.50990184e-02]
 [8.64915183e-02 3.35761903e-01 2.45437406e-01 2.74692510e-01
  7.72964279e-01 5.03165791e-01]]
please enter the num of rows of the first matrix:4
please e